export type EventCategory =
  | "Atividades do clube"
  | "reuniao"
  | "evento-especial"
  | "especialidade"
  | "comunitario"
  | "Visitas"

export interface CalendarEvent {
  id: string
  title: string
  date: string
  endDate?: string
  category: EventCategory
  description: string
  location?: string
  time?: string
}

export const categoryConfig: Record<
  EventCategory,
  { label: string; color: string; bgColor: string }
> = {
  "Atividades do clube": {
    label: "Atividades do Clube",
    color: "bg-emerald-500",
    bgColor: "bg-emerald-500/20",
  },
  reuniao: {
    label: "Reunião",
    color: "bg-blue-500",
    bgColor: "bg-blue-500/20",
  },
  "evento-especial": {
    label: "Evento Especial",
    color: "bg-amber-500",
    bgColor: "bg-amber-500/20",
  },
  especialidade: {
    label: "Especialidade",
    color: "bg-purple-500",
    bgColor: "bg-purple-500/20",
  },
  comunitario: {
    label: "Comunitário",
    color: "bg-rose-500",
    bgColor: "bg-rose-500/20",
  },
  Visitas: {
    label: "Visitas",
    color: "bg-pink-500",
    bgColor: "bg-pink-500/20",
  },
}

export const events2026: CalendarEvent[] = [
  // Janeiro
  
  // Fevereiro
 
  // Março
  {
    id: "7",
    title: "Curso de liderança - 7º Região",
    date: "2026-03-15",
    category: "evento-especial",
    description: "Curso de liderança para capitães, secretários e conselheiros de unidade",
    location: "IASD Central",
    time: "14:00",
  },
  {
    id: "8",
    title: "Caminhada Luzeiro",
    date: "2026-03-22",
    category: "Atividades do clube",
    description: "Caminhada do clube luzeiro",
    location: "--",
    time: "--:--",
  },
  {
    id: "34",
    title: "Reunião da unidade",
    date: "2026-03-18",
    category: "reuniao",
    description: "Reunião da unidade",
    location: "--",
    time: "--:--",
  },
  {
    id: "35",
    title: "Reuinão Regular",
    date: "2026-03-29",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "36",
    title: "Visita",
    date: "2026-03-31",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "--",
    time: "--:--",
  },
  // Abril
  {
    id: "9",
    title: "Visita",
    date: "2026-04-08",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "--",
    time: "--:--",
  },
  {
    id: "10",
    title: "Acampamento da liderança",
    date: "2026-04-10",
    endDate: "2026-04-12",
    category: "Atividades do clube",
    description: "Acampamento para treinamento da liderança do clube",
    location: "--",
    time: "--:--",
  },
  {
    id: "11",
    title: "Reunião da unidade",
    date: "2026-04-16",
    category: "reuniao",
    description: "Reunião da unidade",
    location: "--",
    time: "--:--",
  },
    {
    id: "37",
    title: "Reunião regular",
    date: "2026-04-19",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
    {
    id: "38",
    title: "Visita",
    date: "2026-04-23",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "--",
    time: "--:--",
    
  },
    {
    id: "39",
    title: "Maratona de rua - reunião externa",
    date: "2026-04-26",
    category: "Atividades do clube",
    description: "Maratona de rua para os desbravadores, reunião externa do clube",
    location: "--",
    time: "--:--",
  },
  
  // Maio
  {
    id: "40",
    title: "Classe Bíblica",
    date: "2026-05-02",
    category: "Atividades do clube",
    description: "Inicio da classe bíblica para os desbravadores",
    location: "--",
    time: "--:--",
  },
  {
    id: "12",
    title: "Dia das Mães",
    date: "2026-05-07",
    category: "evento-especial",
    description: "Dia das mães",
    location: "--",
    time: "--:--",
  },
  {
    id: "41",
    title: "Aniversário do clube luzeiro",
    date: "2026-05-09",
    category: "Atividades do clube",
    description: "Aniversário do clube luzeiro",
    location: "IASD Central",
    time: "08:30",
  },
  {
    id: "42",
    title: "Visita",
    date: "2026-05-12",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "--",
    time: "--:--",
  },
  {
    id: "13",
    title: "Reunião regular",
    date: "2026-05-03",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "14",
    title: "Especialidade do caderno de classe",
    date: "2026-05-22",
    category: "especialidade",
    description: "Especialidade do caderno de classe para os desbravadores",
    location: "Local a definir",
    time: "--:--",
  },
  {
    id: "43",
    title: "Reunião regular",
    date: "2026-05-17",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
   {
    id: "44",
    title: "Adolecamp",
    date: "2026-05-23",
    category: "Atividades do clube",
    description: "----",
    location: "---",
    time: "--:--",
  },
  {
    id: "45",
    title: "Reunião regular / Adolecamp",
    date: "2026-05-24",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "46",
    title: "Reunião da unidade",
    date: "2026-05-27",
    category: "reuniao",
    description: "Reunião da unidade",
    location: "--",
    time: "--:--",
  },
  {
    id: "47",
    title: "Pernoite do clube luzeiro",
    date: "2026-05-30",
    endDate: "2026-05-31",
    category: "Atividades do clube",
    description: "Pernoite do clube luzeiro",
    location: "--",
    time: "--:--",
  },
  // Junho
  {
    id: "15",
    title: "Noite de filme",
    date: "2026-06-10",
    category: "evento-especial",
    description: "Noite de filme com a unidade",
    location: "local a definir",
    time: "18:00",
  },
  {
    id: "16",
    title: "Reunião regular",
    date: "2026-06-14",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "48",
    title: "Visita",
    date: "2026-06-16",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "Casa de um desbravador",
    time: "--:--",
  },
    {
    id: "49",
    title: "Reunião regular",
    date: "2026-06-21",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
    {
    id: "50",
    title: "Campuni Distrital",
    date: "2026-06-26",
    endDate: "2026-06-28",
    category: "Atividades do clube",
    description: "Grande encontro distrital de clubes de desbravadores",
    location: "--",
    time: "--:--",
  },
  // Julho

  // Agosto
  {
    id: "19",
    title: "Retorno das atividades",
    date: "2026-08-02",
    category: "Atividades do clube",
    description: "Retorno das atividades",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "20",
    title: "Dia dos Pais",
    date: "2026-08-09",
    category: "evento-especial",
    description: "Dia dos pais - folga",
    location: "--",
    time: "--:--",
  },
  {
    id: "21",
    title: "Visita",
    date: "2026-08-06",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "Casa de um desbravador",
    time: "--:--",
  },
      {
    id: "51",
    title: "Programação dia dos pais",
    date: "2026-08-16",
    category: "evento-especial",
    description: "Programação para o dia dos pais",
    location: "--",
    time: "--:--",
  },
      {
    id: "52",
    title: "Reunião da unidade",
    date: "2026-08-13",
    category: "reuniao",
    description: "Reunião da unidade",
    location: "--",
    time: "--:--",
  },
    {
    id: "53",
    title: "Reunião regular",
    date: "2026-06-23",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
     {
    id: "54",
    title: "Reunião regular",
    date: "2026-06-30",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
  // Setembro
  {
    id: "22",
    title: "Reunião regular",
    date: "2026-09-06",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "23",
    title: "Especialidade",
    date: "2026-09-10",
    category: "especialidade",
    description: "Especialidade do Caderno de classe",
    location: "--",
    time: "--:--",
  },
  {
    id: "24",
    title: "Reunião regular - semana do lenço",
    date: "2026-09-13",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
    {
    id: "55",
    title: "Semana do lenço",
    date: "2026-09-14",
    endDate: "2026-09-18",
    category: "Atividades do clube",
    description: "Semana do lenço",
    location: "--",
    time: "--:--",
  },
   {
    id: "56",
    title: "Dia mundial DBV",
    date: "2026-09-19",
    category: "evento-especial",
    description: "Dia mundial dos desbravadores",
    location: "--",
    time: "--:--",
  },
    {
    id: "57",
    title: "Visita",
    date: "2026-09-23",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "Casa de um desbravador",
    time: "--:--",
  },
    {
    id: "58",
    title: "Reunião regular",
    date: "2026-09-27",
    category: "Atividades do clube",
    description: "Reunião regular do clube",
    location: "IASD Central",
    time: "08:15",
  },
  // Outubro
  {
    id: "25",
    title: "Pernoite da unidade",
    date: "2026-10-02",
    endDate:"2026-10-04",
    category: "evento-especial",
    description: "Pernoite com atividades recreativas e instruções",
    location: "--",
    time: "--:--",
  },
  {
    id: "26",
    title: "Reunião regular",
    date: "2026-10-11",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "27",
    title: "Visita",
    date: "2026-10-14",
    category: "Visitas",
    description: "Visita na casa de um desbravador",
    location: "Casa de um desbravador",
    time: "--:--",
  },
    {
    id: "58",
    title: "Reunião regular",
    date: "2026-10-18",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
  // Novembro
    {
    id: "28",
    title: "Reunião regular",
    date: "2026-11-01",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
      {
    id: "59",
    title: "Reunião regular",
    date: "2026-11-08",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
      {
    id: "60",
    title: "Reunião regular",
    date: "2026-11-15",
    category: "Atividades do clube",
    description: "Reunião regular do clube luzeiro",
    location: "IASD Central",
    time: "08:15",
  },
  {
    id: "29",
    title: "Investidura",
    date: "2026-11-22",
    category: "evento-especial",
    description: "Cerimônia de investidura de novas classes e especialidades",
    location: "IASD Central",
    time: "19:00",
  },
    {
    id: "61",
    title: "COnfraternização da unidade",
    date: "2026-11-28",
    category: "evento-especial",
    description: "Confraternização da unidade Sirius",
    location: "--",
    time: "--:--",
  },
  {
    id: "30",
    title: "Encerramento das Atividades",
    date: "2026-11-29",
    category: "Atividades do clube",
    description: "Encerramento das atividades regulares do clube",
    location: "IASD Central",
    time: "--:--",
  },
  // Dezembro
  {
    id: "31",
    title: "Oscar DBV",
    date: "2026-12-05",
    category: "evento-especial",
    description: "Oscar para premiar os destaques do ano",
    location: "--",
    time: "--:--",
  },
  
]

export const months = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
]

export const weekDays = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"]
